# Generated by Django 2.0.6 on 2018-06-14 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('az_challenges', '0003_challengegroup_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('details', models.CharField(blank=True, default='', max_length=200)),
                ('date_unlocked', models.DateTimeField(auto_now_add=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('challenge_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='az_challenges.ChallengeGroup')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='az_challenges.Member')),
            ],
        ),
    ]
