# Generated by Django 2.0.6 on 2018-06-14 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('az_challenges', '0004_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'activities'},
        ),
    ]
