# Generated by Django 2.0.6 on 2018-06-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('az_challenges', '0005_auto_20180614_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
