# Generated by Django 2.0.6 on 2018-06-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('az_challenges', '0006_auto_20180614_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
