# Generated by Django 2.0.6 on 2018-06-15 07:28

from django.db import migrations

def challenge_type_initial(apps, schema_editor):
	# ref https://docs.djangoproject.com/en/2.0/topics/migrations/#data-migrations
	ChallengeType = apps.get_model('az_challenges', 'ChallengeType')
	
	# New challenge type for A-Z challenges
	challenge_type_az = ChallengeType()
	challenge_type_az.name = 'A-Z Challenge'
	challenge_type_az.save()
	
	# Custom challenge type	
	challenge_type_custom = ChallengeType()
	challenge_type_custom.name = 'Custom'
	challenge_type_custom.save()
	

class Migration(migrations.Migration):

    dependencies = [
        ('az_challenges', '0007_challengetype'),
    ]

    operations = [
		migrations.RunPython(challenge_type_initial),
    ]
