# Generated by Django 2.0.6 on 2018-06-15 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('az_challenges', '0008_auto_20180615_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengegroup',
            name='challenge_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='az_challenges.ChallengeType'),
            preserve_default=False,
        ),
    ]
