# Generated by Django 2.0.6 on 2018-06-15 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('az_challenges', '0009_challengegroup_challenge_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('challenge_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='az_challenges.ChallengeType')),
            ],
        ),
    ]
