# Generated by Django 2.0.6 on 2018-06-15 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('az_challenges', '0011_auto_20180615_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='az_challenges.ActivityType'),
            preserve_default=False,
        ),
    ]
